name: ImmortalWrt 24.10 S922X 构建（直连优化版）

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 空间检查 & 清理
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: 安装依赖（Ubuntu 24.04 优化）
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync subversion \
            swig unzip zlib1g-dev ccache quilt time
          # 验证依赖
          python3 -m setuptools --version
          git --version

      - name: 克隆 ImmortalWrt（直连 + 重试）
        run: |
          cd $GITHUB_WORKSPACE
          for i in {1..3}; do
            echo "第 $i 次尝试克隆..."
            if git clone --depth 1 -b openwrt-24.10 \
              https://github.com/immortalwrt/immortalwrt.git openwrt; then
              echo "克隆成功！"
              break
            fi
            sleep 5
          done || { echo "克隆失败"; exit 1; }
          cd openwrt
          ln -sf ../config/.config .config
          ls -la

      - name: 下载 u-boot（官方源）
        run: |
          cd openwrt
          mkdir -p files/u-boot
          wget -q https://github.com/immortalwrt/immortalwrt/raw/openwrt-24.10/target/linux/meson/image/u-boot-s922x.bin \
            -O files/u-boot/u-boot-s922x.bin || { echo "u-boot 下载失败"; exit 1; }
          ls -lh files/u-boot/

      - name: 更新 & 安装 feeds（直连）
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 缓存 dl 目录（加速）
        uses: actions/cache@v4
        with:
          path: openwrt/dl
          key: dl-${{ runner.os }}-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: dl-${{ runner.os }}-

      - name: 应用配置
        run: |
          cd openwrt
          make defconfig

      - name: 开始编译（单核 + 日志）
        run: |
          cd openwrt
          make -j1 V=s 2>&1 | tee build.log || { tail -50 build.log; exit 1; }

      - name: 上传固件
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-S922X-Firmware
          path: |
            openwrt/bin/targets/meson/g12b/*.bin
            openwrt/bin/targets/meson/g12b/*.img*
            openwrt/bin/targets/meson/g12b/*.tar.gz
          retention-days: 7

      - name: 上传日志（始终）
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt/build.log
          if-no-files-found: warn
