name: ImmortalWrt 24.10 S922X 构建

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 空间清理
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: 安装依赖（修复 python3-distutils）
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools python3-pip rsync subversion \
            swig unzip zlib1g-dev ccache quilt time aria2

      - name: 克隆 ImmortalWrt（镜像 + 重试 + 浅克隆）
        run: |
          for i in {1..3}; do
            echo "第 $i 次尝试克隆..."
            git clone --depth 1 -b openwrt-24.10 \
              https://ghproxy.com/https://github.com/immortalwrt/immortalwrt.git openwrt && break
            sleep 10
          done
          [ -d "openwrt" ] && echo "克隆成功" || (echo "克隆失败" && exit 1)

      - name: 验证目录
        run: |
          ls -la
          [ -d "openwrt" ] && echo "openwrt 目录存在" || (echo "目录缺失" && exit 1)

      - name: 配置 .config
        run: |
          cd openwrt
          ln -sf ../config/.config .config
          cat .config

      - name: 下载 u-boot（镜像加速）
        run: |
          cd openwrt
          mkdir -p files/u-boot
          wget -t 3 -T 30 \
            https://ghproxy.com/https://github.com/immortalwrt/immortalwrt/raw/master/target/linux/meson/image/u-boot-s922x.bin \
            -O files/u-boot/u-boot-s922x.bin || \
          wget -t 3 -T 30 \
            https://github.com/immortalwrt/immortalwrt/raw/master/target/linux/meson/image/u-boot-s922x.bin \
            -O files/u-boot/u-boot-s922x.bin
          ls -l files/u-boot/

      - name: 更新 feeds（镜像加速）
        run: |
          cd openwrt
          sed -i 's|github.com|ghproxy.com/https://github.com|g' feeds.conf.default
          ./scripts/feeds update -a || ./scripts/feeds update -a

      - name: 安装 feeds
        run: |
          cd openwrt
          ./scripts/feeds install -a

      - name: 缓存 dl
        uses: actions/cache@v3
        with:
          path: openwrt/dl
          key: dl-${{ runner.os }}-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: dl-${{ runner.os }}-

      - name: 应用配置
        run: |
          cd openwrt
          make defconfig

      - name: 开始编译（单核 + 日志）
        run: |
          cd openwrt
          make -j1 V=s 2>&1 | tee build.log

      - name: 上传固件
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-S922X-Firmware
          path: |
            openwrt/bin/targets/meson/g12b/*.bin
            openwrt/bin/targets/meson/g12b/*.img*
          retention-days: 7

      - name: 上传日志（失败）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failed-log
          path: openwrt/build.log
