name: ImmortalWrt 24.10 S922X 构建（目标加载修复版）

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 240

    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 空间检查 & 清理
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: 安装依赖
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential clang flex bison g++ gawk \
            gcc-multilib gettext git libncurses5-dev libssl-dev \
            python3-setuptools rsync subversion \
            swig unzip zlib1g-dev ccache quilt time
          python3 -c "import setuptools; print('setuptools version:', setuptools.__version__)"

      - name: 克隆 ImmortalWrt
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth 1 -b openwrt-24.10 \
            https://github.com/immortalwrt/immortalwrt.git openwrt
          cd openwrt
          cp ../config/.config .config  # cp 而非 ln，避免符号链接问题
          ls -la .config
          echo "目标配置加载: $(head -5 .config | grep -i target)"

      - name: 下载 u-boot
        run: |
          cd openwrt
          mkdir -p files/u-boot
          wget -q https://raw.githubusercontent.com/immortalwrt/immortalwrt/openwrt-24.10/target/linux/meson/files/u-boot-s922x.bin \
            -O files/u-boot/u-boot-s922x.bin
          ls -lh files/u-boot/

      - name: 更新 & 安装 feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 缓存 dl & ccache
        uses: actions/cache@v4
        with:
          path: |
            openwrt/dl
            ~/.ccache
          key: cache-${{ runner.os }}-${{ hashFiles('openwrt/feeds.conf.default') }}
          restore-keys: cache-${{ runner.os }}-

      - name: 应用配置（oldconfig 加载自定义）
        run: |
          cd openwrt
          make oldconfig  # 加载 .config 而非覆盖

      - name: 开始编译
        run: |
          cd openwrt
          export CCACHE_DIR=~/.ccache
          make -j1 V=s 2>&1 | tee build.log || { tail -50 build.log; exit 1; }

      - name: 上传固件（动态路径）
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt-S922X-Firmware
          path: |
            openwrt/bin/targets/meson/g12b/s922x/*.*  # 所有固件
          retention-days: 7

      - name: 上传日志（始终）
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: openwrt/build.log
          if-no-files-found: warn
